O = obj

CPPFLAGS = -DMM_MAJOR=$(MM_MAJOR) -DMM_MINOR=$(MM_MINOR)

.SUFFIXES: .cc

.cc.obj:
	$(COMPILER) $(CPPFLAGS) $<

OBJS = misc.$(O) resource.$(O) mmail.$(O) driverl.$(O) filelist.$(O) \
area.$(O) letter.$(O) read.$(O) compress.$(O) pktbase.$(O) bw.$(O) \
qwk.$(O) omen.$(O) soup.$(O) opx.$(O)

!include depend

mm-main: $(OBJS)
