O = obj

CPPFLAGS = -DCURS_INC=$(CURS_INC) -DMM_MAJOR=$(MM_MAJOR) \
-DMM_MINOR=$(MM_MINOR)

.cc.obj:
	$(CC) -c -P $(CPPFLAGS) $<

OBJS = mmcolor.$(O) mysystem.$(O) isoconv.$(O) basic.$(O) interfac.$(O) \
packet.$(O) arealist.$(O) letterl.$(O) letterw.$(O) lettpost.$(O) \
ansiview.$(O) addrbook.$(O) tagline.$(O) help.$(O) main.$(O)

!include depend

intrfc: $(OBJS)
